apiVersion: apps/v1
kind: Deployment
metadata:
  name: tz0rk-bot
  labels:
    app: tz0rk-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tz0rk-bot
  template:
    metadata:
      labels:
        app: tz0rk-bot
    spec:
      containers:
        - name: tz0rk
          image: quay.io/nicholas_lane/tz0rk:0.0.1
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: 128Mi
              cpu: 100m
